# Generated by Django 2.1.3 on 2018-12-03 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Estacionamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('costo', models.IntegerField(default=0)),
                ('latitud', models.DecimalField(decimal_places=7, default=0, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=7, default=0, max_digits=9)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.Departamento')),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.Distrito')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.Departamento')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.Pais')),
            ],
        ),
        migrations.AddField(
            model_name='estacionamiento',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.Pais'),
        ),
        migrations.AddField(
            model_name='estacionamiento',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.Provincia'),
        ),
        migrations.AddField(
            model_name='distrito',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.Pais'),
        ),
        migrations.AddField(
            model_name='distrito',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.Provincia'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.Pais'),
        ),
    ]
